name: Publish posts from Issues

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  schedule:
    - cron: '0 9 * * *'   # optional daily sweep

permissions:
  contents: write
  issues: read

jobs:
  build-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pyyaml requests

      - name: Convert Issues -> Jekyll posts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python scripts/issues_to_posts.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Publish/update posts from issues"
          git push
